# Generated by Django 4.0.6 on 2022-10-11 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField(max_length=30)),
                ('time_reservation', models.CharField(choices=[('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], default='18:00', max_length=30)),
                ('name_client', models.CharField(max_length=100)),
                ('email_client', models.EmailField(max_length=200, unique=True)),
                ('phonenumber_client', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('numberofpeople', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='2', max_length=2)),
                ('reservation_code', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', editable=False, length=7, max_length=10, prefix='')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
