# Generated by Django 4.0.6 on 2022-10-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='email_client',
            field=models.EmailField(max_length=200),
        ),
    ]
